--- 

- name: compose the oracle automated installer settings
  template:
    src: wg_installSoftwareOnly.rsp.j2
    dest: "/tmp/wg_install.rsp"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    
- name: install WebGate
  become_user: "{{ oracle_user }}"
  command: "{{ download_folder }}/wg/Disk1/runInstaller -silent -force -ignoreSysPrereqs -jreLoc {{ jdk_home }} -waitforcompletion -responseFile /tmp/wg_install.rsp"
  ignore_errors: yes
  when: not st.stat.exists  
