---

- name: Check if Identity Store has been configured.
  stat: path={{ domain_location }}
  register: st

- name: Assures /tmp/domain exists
  file: path="/tmp/domain" state=directory owner="{{ oracle_user }}" group="{{ oracle_group }}"
  when: not st.stat.exists 

- name: copy utlis.py
  copy: src=utils.py dest=/tmp/domain/utils.py owner="{{ oracle_user }}" group="{{ oracle_group }}" mode=0644
  when: not st.stat.exists 
  
- name: compose the oracle domain script
  template:
    src: createDomain.py.j2
    dest: "/tmp/domain/createDomain.py"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  when: not st.stat.exists 

- name: Create Domain
  become_user: "{{ oracle_user }}"
  command: "{{ iam_home }}/common/bin/wlst.sh /tmp/domain/createDomain.py"
  when: not st.stat.exists 
  
- name: Configure OPSS
  become_user: "{{ oracle_user }}"
  command: "{{ fmw_home }}/oracle_common/common/bin/wlst.sh {{ iam_home }}/common/tools/configureSecurityStore.py -d {{domain_location}} -c IAM -p {{db_opss_password}} -m create"
  when: not st.stat.exists 
